/**
 * partner-kit/sign.mjs — ed25519 signing with DACS domain separation, zero dependencies.
 *
 * NON-NORMATIVE partner-kit port of `src/lib/sign.ts` (pathos-dacs-ref). The reference
 * impl signs via @noble/ed25519; this kit uses node:crypto's native Ed25519 (RFC 8032 —
 * deterministic, so both produce byte-identical signatures; the kit's sign vectors were
 * generated by the reference impl and MUST reproduce here, which IS the cross-impl check).
 *
 * Raw 32-byte keys are converted to/from DER at the boundary:
 *  - private (PKCS#8):  302e020100300506032b657004220420 || raw32
 *  - public  (SPKI):    302a300506032b6570032100        || raw32
 */
import { createPrivateKey, createPublicKey, generateKeyPairSync, sign as cryptoSign, verify as cryptoVerify } from 'node:crypto';
import { buildSignedBytes, assertKnownSeparator, assertEmittableSeparator } from './domain-sep.mjs';

const PKCS8_ED25519_PREFIX = Buffer.from('302e020100300506032b657004220420', 'hex');
const SPKI_ED25519_PREFIX = Buffer.from('302a300506032b6570032100', 'hex');

function privKeyObject(privRaw32) {
  if (!(privRaw32 instanceof Uint8Array) || privRaw32.length !== 32) {
    throw new Error('ed25519 private key must be 32 raw bytes');
  }
  return createPrivateKey({
    key: Buffer.concat([PKCS8_ED25519_PREFIX, Buffer.from(privRaw32)]),
    format: 'der',
    type: 'pkcs8',
  });
}

function pubKeyObject(pubRaw32) {
  if (!(pubRaw32 instanceof Uint8Array) || pubRaw32.length !== 32) {
    throw new Error('ed25519 public key must be 32 raw bytes');
  }
  return createPublicKey({
    key: Buffer.concat([SPKI_ED25519_PREFIX, Buffer.from(pubRaw32)]),
    format: 'der',
    type: 'spki',
  });
}

/** Derive the raw 32-byte public key from a raw 32-byte private key. */
export function publicKeyFromPrivate(privRaw32) {
  const pubDer = createPublicKey(privKeyObject(privRaw32)).export({ format: 'der', type: 'spki' });
  return new Uint8Array(pubDer.subarray(pubDer.length - 32));
}

/**
 * Sign `body` under `separator` (optionally with `intermediateHash` for composite forms).
 * Throws on separators outside the §B.7 registry and on read-only legacy separators
 * (emission closure) — identical discipline to src/lib/sign.ts.
 */
export function sign(separator, body, privKey, intermediateHash) {
  assertEmittableSeparator(separator);
  const signedBytes = buildSignedBytes(separator, body, intermediateHash);
  return new Uint8Array(cryptoSign(null, Buffer.from(signedBytes), privKeyObject(privKey)));
}

/**
 * Verify `sig` over `body` under `separator`. Returns false (never throws) on unknown
 * separator or any crypto error — identical semantics to src/lib/sign.ts. Read-only
 * legacy separators ARE admitted here (verify/read path).
 */
export function verify(separator, sig, body, pubKey, intermediateHash) {
  try {
    assertKnownSeparator(separator);
  } catch {
    return false;
  }
  try {
    const signedBytes = buildSignedBytes(separator, body, intermediateHash);
    return cryptoVerify(null, Buffer.from(signedBytes), pubKeyObject(pubKey), Buffer.from(sig));
  } catch {
    return false;
  }
}

/** Generate a fresh ed25519 keypair (raw 32-byte forms). */
export function generateKeypair() {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const privDer = privateKey.export({ format: 'der', type: 'pkcs8' });
  const pubDer = publicKey.export({ format: 'der', type: 'spki' });
  return {
    privKey: new Uint8Array(privDer.subarray(privDer.length - 32)),
    pubKey: new Uint8Array(pubDer.subarray(pubDer.length - 32)),
  };
}
